name: PHP

on: [push]

jobs:
  build:
    name: "PHP"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setting MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql root password: "test"
          mysql database: 'test'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Migrate databases
        run: php artisan migrate
      - name: Run seeds
        run: php artisan db:seed
      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Upload report to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      - name: Execute tests for CodeClimate
        uses: paambaati/codeclimate-action@v2.5.3
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: vendor/bin/phpunit --coverage-clover=coverage.xml
          coverageLocations:
            "./coverage.xml:clover"
          prefix: "${{github.workspace}}"
